spring:
  application:
    name: itoken-config
 # boot:
    #admin:
    #  client:
    #    url: http://localhost:8084
  cloud:
    config:
      label: master    #主分支
      server:
        git:
          uri: https://github.com/foverTEC/itoken-itoken-config.git
          search-paths: respo
          username: 1203611441@qq.com
          password: zb100519zfj
 # zipkin:
   # base-url: http://localhost:9411

server:
  port: 8888

#配置服务注册到eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info