spring:
  application:
    name: itoken-uul


server:
  port: 8769

#将服务注册到eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 路由网关聚合所用的服务暴露给前端调用api
zull:
  roures:
    api-a:
      path: /api/a/**
      serviceId:  #服务名称 一种映射关系
    api-b:
      path: /api/b/**
      serviceId:





